### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by iocmet** [fnuecke/oc2#148]
java.lang.AssertionError: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @11e67f7a
	at li.cil.sedna.riscv.R5CPUGenerator.generateClass(R5CPUGenerator.java:110)
	at li.cil.sedna.riscv.R5CPUGenerator.<clinit>(R5CPUGenerator.java:26)
	at li.cil.sedna.riscv.R5CPU.create(R5CPU.java:13)
	at li.cil.sedna.riscv.R5CPU.create(R5CPU.java:17)
	at li.cil.sedna.riscv.R5Board.<init>(R5Board.java:58)
	at li.cil.oc2.common.vm.AbstractVirtualMachine.<init>(AbstractVirtualMachine.java:71)
	at li.cil.oc2.common.tileentity.ComputerTileEntity$ComputerVirtualMachine.<init>(ComputerTileEntity.java:389)
	at li.cil.oc2.common.tileentity.ComputerTileEntity$ComputerVirtualMachine.<init>(ComputerTileEntity.java:385)
	at li.cil.oc2.common.tileentity.ComputerTileEntity.<init>(ComputerTileEntity.java:77)
	at net.minecraft.tileentity.TileEntityType.func_200968_a(TileEntityType.java:89)
	at li.cil.oc2.common.block.ComputerBlock.createTileEntity(ComputerBlock.java:98)

**Comment by lxhom** [comment]
I think this may be an issue with your Java installation, it would be helpful if you post the full crash log from the launcher or from the .minecraft directory if it's not in the launcher anymore which provides more info about your system.

**Comment by fnuecke** [comment]
Yes, please provide the full log or at least system information, i.e. Java version and flavor used etc.

**Comment by iocmet** [comment]
I lost the log

**Comment by fnuecke** [comment]
Then I'm afraid there's not much I can do, sorry. If it happens again, please create a new ticket.
